package com.splicemachine.test.diff;

import com.splicemachine.test.utils.TestUtils;
import com.splicemachine.test.verify.Verifier;
import com.splicemachine.test.verify.VerifyReport;
import difflib.DiffUtils;
import difflib.Patch;

import java.io.File;
import java.util.ArrayList;
import java.util.Collection;
import java.util.Collections;
import java.util.List;

/**
 * Static utility to determine and report file differences
 */
public class DiffEngine implements Verifier {
	private final String testInputDir;
	private final List<String> derbyFilter;
	private final List<String> spliceFilter;

    /**
     * @param testInputDir the directory in which to look for SQL scripts (input)
	 * @param derbyOutputFilter any optional output line filters to apply to Derby output.
	 * @param spliceOutputFilter any optional output line filters to apply to Splice output.
     */
	public DiffEngine(String testInputDir, 
			List<String> derbyOutputFilter, List<String> spliceOutputFilter) {
		this.testInputDir = testInputDir;
		this.derbyFilter = derbyOutputFilter;
		this.spliceFilter = spliceOutputFilter;
	}

	/**
     * Calculate the differences of the output generated by all the given SQL scripts.
     * @param sqlFiles SQL script files that were executed against Derby and Splice
     *                 to produce output residing in <code>testOutputDir</code>
     * @return the list of {@link DiffReport}s
     */
    @Override
    public List<VerifyReport> verifyOutput(List<File> sqlFiles) {

        List<VerifyReport> diffs = new ArrayList<VerifyReport>();

        for (File sqlFile: sqlFiles) {
            // derby output
            String derbyFileName = testInputDir + sqlFile.getName().replace(".sql", TestUtils.DERBY_OUTPUT_EXT);
            // NOTE: we need ALL lines, including "--" comments because
            // there are differencing directives in there
            List<String> derbyFileLines = TestUtils.fileToLines(derbyFileName, (String)null);
            // filter derby warnings, etc
            derbyFileLines = filterOutput(derbyFileLines, derbyFilter);

            // splice output
            String spliceFileName = testInputDir + sqlFile.getName().replace(".sql", TestUtils.SPLICE_OUTPUT_EXT);
            // NOTE: we need ALL lines, including "--" comments because
            // there are differencing directives in there
            List<String> spliceFileLines = TestUtils.fileToLines(spliceFileName, (String)null);
            // filter splice warnings, etc
            spliceFileLines = filterOutput(spliceFileLines, spliceFilter);

            // Diff the output files using a custom Equalizer
            Patch<String> patch = DiffUtils.diff(derbyFileLines, spliceFileLines, new LineEqualizer());

            // Create a diff report for this SQL script output
            DiffReport diff = new DiffReport(derbyFileName, spliceFileName, patch.getDeltas());
            diffs.add(diff);
        }
        return diffs;
    }

    /**
     * Remove (filter) any lines in <code>fileLines</code> that contain any occurrences of
     * <code>lineFilters</code>
     * <p>
     *     This method is used to filter lines from one output file that are not in the
     *     other.  Lines in one file that ARE NOT in the other throw off diff comparison
     *     by one line.<br/>
     *     <b>NEVER</b> use this method to filter lines from one output file that are also
     *     in the other, unless you filter the same lines from the other.
     * </p>
     * @param fileLines the strings to consider
     * @param lineFilters patterns, occurrences of which, should be filtered.
     * @return the result of the <code>fileLines</code> filtering (lines with lineFilters
     * removed).
     */
    public static List<String> filterOutput(List<String> fileLines, List<String> lineFilters) {
        if (isEmpty(fileLines) || isEmpty(lineFilters)) {
            return fileLines;
        }
        List<String> copy = Collections.synchronizedList(new ArrayList<String>(fileLines));
        List<String> filteredLines = Collections.synchronizedList(new ArrayList<String>(fileLines.size()));
        for (String line : copy) {
            boolean filter = false;

            for (String warning : lineFilters) {
                if (line.contains(warning)) {
                    filter = true;
                    break;
                }
            }
            if (! filter) {
                filteredLines.add(line);
            }
        }
        return filteredLines;
    }

    private static boolean isEmpty(Collection<? extends Object> objects) {
        return (objects == null || objects.isEmpty());
    }

}
