#!/bin/bash

# Cloudera VM Splice Machine DB cleaner

echo "Cleaning Splice Machine Cloudera DB"

# TODO Use zookeeper's cli to rmr /startupPath, then bounce hbase
# see also, SpliceMasterObserver.createSplice()

. ./lib/setEnv

./lib/stop

$ZOOKEEPER_HOME/bin/zkCli.sh <<flattenZoo
ls /
rmr /hbase
rmr /conglomerates
rmr /transactions
rmr /derbyPropertyPath
rmr /queryNodePath
rmr /spliceTasks
rmr /spliceJobs
rmr /startupPath
ls /
flattenZoo

./lib/start
