#!/bin/bash

# Cloudera VM Splice Machine starter

echo "Starting Splice Machine on Cloudera"

sudo $HBASE_HOME/bin/hbase-daemon.sh --config conf start master
sudo $HBASE_HOME/bin/hbase-daemon.sh --config conf start regionserver
