#!/bin/bash

# Cloudera VM Splice Machine installer

. ./lib/setEnv

echo "Stopping Splice Machine on $SPLICE_ENV"

curl -X POST -u admin:admin 'http://localhost:7180/api/v1/clusters/Cluster%201%20-%20CDH4/services/hbase1/commands/stop'

echo "curl -u admin:admin 'http://localhost:7180/api/v1/commands/<cmdId>'"
