#!/bin/bash

# Cloudera VM Splice Machine installer

. ./lib/setEnv

echo "Stopping Splice Machine on $SPLICE_ENV"

sudo $HBASE_HOME/bin/hbase-daemon.sh stop regionserver
sudo $HBASE_HOME/bin/hbase-daemon.sh stop master
