#!/bin/bash

# Cloudera VM Splice Machine installer

. ./lib/setEnv

echo "Stopping Splice Machine on $SPLICE_ENV"

distMode=`sudo $HBASE_HOME/bin/hbase --config "$HBASE_CONF_DIR" org.apache.hadoop.hbase.util.HBaseConfTool hbase.cluster.distributed | head -n 1`

if [ "$distMode" == 'false' ]; then
  echo "  Not running in cluster"
else
  echo "  Running in cluster"
fi

sudo service cloudera-scm-server stop

#sudo $HBASE_HOME/bin/hbase-daemon.sh --config $HBASE_HOME/conf/ stop regionserver
#sudo $HBASE_HOME/bin/hbase-daemon.sh --config $HBASE_HOME/conf/ stop master
