rm(data)
rm(c1)
rm(c2)
rm(h1)
rm(h2)
data <- read.csv("/Users/scottfines/workspace/temp/data.csv")
c1 <- unlist(data[c(1)])
c2 <- unlist(data[c(2)])
h1 <- hist(c1)
h2 <- hist(c2)
plot( h1, col=rgb(0,0,1,1/4))
plot( h2, col=rgb(1,0,0,1/4),add=T)
