#!/bin/bash

usage() {
    # $1 is an error, if any
    if [ ! -z "$1" ] 
        then
        echo "Error: $1"
    fi
    echo "Usage: $0 {-install | -start | -stop | -restart | -clean | -splice}"
    echo "Where: "
    echo "  -state => check the service state"
    echo "  -install => install the splice complete jar and coprocessors"
    echo "  -start => start HBase"
    echo "  -stop => stop HBase"
    echo "  -restart => bounce HBase"
    echo "  -clean => clean the splice DB"
    echo "  -splice => start the splice SQL shell"
}

case $1 in
 -h | -help | -\?)
     usage
     exit 0      # This is not an error, User asked help. Don't do "exit 1"
     ;;
 -state)
     # call platform-specific service checker
     ./lib/serviceState
     ;;
 -install)
     # call platform-specific installer
     ./lib/install
     ;;
 -start)
     # call platform-specific HBase starter
     ./lib/start
     ;;
 -stop)
     # call platform-specific HBase stopper
     ./lib/stop
     ;;
 -restart)
     # call platform-specific HBase stopper
     ./lib/stop
     # TODO: remove sleep - only using to wait for Cloudera to stop
     sleep 30s
     # call platform-specific HBase starter
     ./lib/start
     ;;
 -clean)
     # call DB cleaner
     ./lib/clean
     ;;
 -splice)
     # call splice shell
     ./lib/splice
     ;;
 *)
     usage "Unknown option (ignored): $1"
     exit 1
     ;;
esac
