
CALL SYSCS_UTIL.SYSCS_DROP_USER('"Joe"');

CALL SYSCS_UTIL.SYSCS_DROP_USER('"Fred"');

DROP VIEW AUTH_FRED.VIEW1;

DROP TABLE IF EXISTS AUTH_FRED.TWO_INT_TABLE2;

DROP TABLE IF EXISTS AUTH_FRED.ONE_INT_TABLE;

DROP TABLE IF EXISTS AUTH_FRED.TWO_INT_TABLE;

DROP SCHEMA AUTH_FRED RESTRICT;

DROP SCHEMA AUTH_JOE RESTRICT;

