@Library('jenkins-shared-library')_

properties([    
    // Job parameter defintions.
    parameters([
        stringParam(
            description: 'Sprint number to build',
            name: 'BUILD_NUM',
            defaultValue: ''
        )
    ])
])

// Define params
def BUILD_NUM = "${params.BUILD_NUM}"
def slackResponse = slackSend(channel: "db-automated-testing", message: "Launching $JOB_NAME pipeline")
slackSend(channel: slackResponse.threadId, message: "Launching Jenkins node...")

node('spliceengine') {
  // run tests
  try {
    def artifact_values  = [
        [$class: 'VaultSecret', path: "secret/aws/jenkins/colo_jenkins", secretValues: [
            [$class: 'VaultSecretValue', envVar: 'ARTIFACT_USER', vaultKey: 'user'],
            [$class: 'VaultSecretValue', envVar: 'ARTIFACT_PASSWORD', vaultKey: 'pass']]],
        [$class: 'VaultSecret', path: "secret/aws/jenkins/splicemachine", secretValues: [
            [$class: 'VaultSecretValue', envVar: 'build_secret_key_id', vaultKey: 'access'],
            [$class: 'VaultSecretValue', envVar: 'build_secret_key', vaultKey: 'secret']]],
    ]
    slackSend(channel: slackResponse.threadId, message: "Assembling secrets and variables...")
    stage('Build Login') {
        wrap([$class: 'VaultBuildWrapper', vaultSecrets: artifact_values]) {
            sh "aws configure set aws_access_key_id $build_secret_key_id"
            sh "aws configure set aws_secret_access_key $build_secret_key"
            sh "aws configure set region us-east-1"
        }
    }
    slackSend(channel: slackResponse.threadId, message: "Checking out code...")
    stage('Checkout') {
      checkout([  
            $class: 'GitSCM', 
            branches: [[name: 'refs/heads/DB-10092']], 
            doGenerateSubmoduleConfigurations: false, 
            extensions: [[$class: 'RelativeTargetDirectory', relativeTargetDir: 'infrastructure-support']], 
            submoduleCfg: [], 
            userRemoteConfigs: [[credentialsId: '88647ede-744a-444b-8c08-8313cc137944', url: 'https://github.com/splicemachine/infrastructure-support.git']]
      ])
      checkout([  
            $class: 'GitSCM', 
            branches: [[name: 'refs/heads/master']], 
            doGenerateSubmoduleConfigurations: false, 
            extensions: [[$class: 'RelativeTargetDirectory', relativeTargetDir: 'infrastructure-support/build-support/scripts/standalone/spliceengine']], 
            submoduleCfg: [], 
            userRemoteConfigs: [[credentialsId: '88647ede-744a-444b-8c08-8313cc137944', url: 'https://github.com/splicemachine/spliceengine.git']]
      ])
    }


    slackSend(channel: slackResponse.threadId, message: "Inject Env Variables...")
    stage('Inject Env Variables') {
        wrap([$class: 'VaultBuildWrapper', vaultSecrets: artifact_values]) {
            dir('infrastructure-support/build-support/scripts/standalone/spliceengine'){
                sh """
                    mkdir -p  ~/.m2/
                    cp pipelines/template/settings.xml ~/.m2/settings.xml
                    sed  -i "s/REPLACE_USER/${ARTIFACT_USER}/" ~/.m2/settings.xml
                    sed  -i "s/REPLACE_PASS/${ARTIFACT_PASSWORD}/" ~/.m2/settings.xml
                """
            }
        }
      dir('infrastructure-support/build-support/scripts/standalone/'){
        sh "sed -i 's/buildNum=/buildNum=${BUILD_NUM}/' standalone.sh"
      }
      currentBuild.result = "SUCCESS"
    }

    slackSend(channel: slackResponse.threadId, message: "Building standalone package...")
    stage('Run Build') {
      dir('infrastructure-support/build-support/scripts/standalone/'){
        sh'''
        ./standalone.sh
        tar xvf SPLICEMACHINE-${BUILD_NUM}.standalone.tar.gz
        export PYTHONPATH=$WORKSPACE:$PYTHONPATH
        export JAVA_HOME=/usr/lib/jvm/jre-openjdk
        export M2_HOME=/opt/maven
        export ANT_HOME=/opt/ant
        export MAVEN_HOME=/opt/maven
        export PATH=/opt/ant/bin:/opt/maven/bin:${PATH}:${PATH}
        ls
        python3 unit_test.py
        '''
      }
    }

    slackSend(channel: slackResponse.threadId, message: "Pushing to S3...")
    stage('Push to S3') {
      dir('infrastructure-support/build-support/scripts/standalone/'){
        sh'''
        aws s3 cp SPLICEMACHINE-${BUILD_NUM}.standalone.tar.gz s3://splice-releases/standalone/ --acl public-read
        '''
      }
    }
  } catch (any) {
    // if there was an exception thrown, the build failed
    currentBuild.result = "FAILED"
    throw any
  } finally {
    archiveArtifacts artifacts: 'infrastructure-support/build-support/scripts/standalone/*.tar.gz'
    slackSend(channel: slackResponse.threadId, message: "$JOB_NAME job status: $currentBuild.result $BUILD_URL")
    // success or failure, always send notifications
    notifyBuild(currentBuild.result)
  }
}
