/*
 * Copyright (c) 2012 - 2020 Splice Machine, Inc.
 *
 * This file is part of Splice Machine.
 * Splice Machine is free software: you can redistribute it and/or modify it under the terms of the
 * GNU Affero General Public License as published by the Free Software Foundation, either
 * version 3, or (at your option) any later version.
 * Splice Machine is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the GNU Affero General Public License for more details.
 * You should have received a copy of the GNU Affero General Public License along with Splice Machine.
 * If not, see <http://www.gnu.org/licenses/>.
 */

package com.splicemachine.si.txn;

import java.util.ArrayList;
import java.util.HashSet;
import java.util.Random;
import java.util.Set;

public class ScriptGen {
    public static void main(String[] args) {
        final int OP_COUNT = 1000;
        final int MAX_ID = 100;
        final int MAX_AGE = 100;

        System.out.println("create table person (id int, age int);");
        System.out.println("autocommit off;");

        Set<Integer> ids = new HashSet<Integer>();
        final Random random = new Random();
        for (int i = 0; i< OP_COUNT; i++) {
            String op = null;
            boolean commit;
            if (percent(random, 10)) {
                commit = false;
            } else {
                commit = true;
            }
            if(percent(random, 10)) {
                if (ids.size() > 0) {
                    final int index = random.nextInt(ids.size());
                    final int id = (Integer) new ArrayList(ids).get(index);
                    if (commit) {
                        ids.remove(id);
                    }
                    op = "delete from person where id = " + id;
                }
            } else {
                final int id = random.nextInt(MAX_ID);
                final int age = random.nextInt(MAX_AGE);
                if (ids.contains(id)) {
                    op = "update person set age = " + age + " where id = " + id;
                } else {
                    if (commit) {
                        ids.add(id);
                    }
                    op = "insert into person (id, age) values (" + id + ", " + age + ")";
                }
            }
            if (op != null) {
                StringBuilder c = new StringBuilder();
                c.append(op);
                c.append(";\n");
                if(commit) {
                    c.append("commit;\n");
                } else {
                    c.append("rollback;\n");
                }
                System.out.print(c);
            }
        }
    }

    private static boolean percent(Random random, int percent) {
        return random.nextInt(100) < percent;
    }
}

/*

create table person (id int, age int);
autocommit off;
insert into person (id, age) values (79, 49);
commit;
insert into person (id, age) values (4, 34);
commit;
insert into person (id, age) values (57, 39);
rollback;
delete from person where id = 79;
commit;
insert into person (id, age) values (9, 9);
commit;
delete from person where id = 9;
commit;
insert into person (id, age) values (97, 50);
commit;
insert into person (id, age) values (95, 17);
commit;
delete from person where id = 97;
commit;
insert into person (id, age) values (75, 78);
commit;
delete from person where id = 4;
commit;
insert into person (id, age) values (21, 1);
commit;
insert into person (id, age) values (67, 44);
commit;
insert into person (id, age) values (62, 21);
commit;
delete from person where id = 95;
commit;
insert into person (id, age) values (38, 39);
commit;
insert into person (id, age) values (83, 53);
commit;
update person set age = 66 where id = 21;
commit;
insert into person (id, age) values (20, 37);
commit;
insert into person (id, age) values (42, 10);
commit;
insert into person (id, age) values (1, 9);
commit;
insert into person (id, age) values (55, 24);
commit;
insert into person (id, age) values (47, 67);
commit;
insert into person (id, age) values (39, 41);
commit;
insert into person (id, age) values (93, 68);
commit;
insert into person (id, age) values (56, 18);
commit;
insert into person (id, age) values (7, 86);
rollback;
insert into person (id, age) values (25, 66);
commit;
delete from person where id = 75;
commit;
insert into person (id, age) values (28, 18);
commit;
update person set age = 40 where id = 42;
commit;
insert into person (id, age) values (63, 61);
rollback;
update person set age = 95 where id = 56;
commit;
insert into person (id, age) values (78, 36);
commit;
insert into person (id, age) values (36, 88);
commit;
insert into person (id, age) values (22, 4);
commit;
insert into person (id, age) values (53, 17);
commit;
update person set age = 81 where id = 62;
commit;
insert into person (id, age) values (10, 13);
commit;
insert into person (id, age) values (80, 68);
commit;
insert into person (id, age) values (34, 32);
commit;
insert into person (id, age) values (14, 11);
commit;
insert into person (id, age) values (51, 29);
commit;
insert into person (id, age) values (17, 73);
commit;
insert into person (id, age) values (99, 14);
commit;
update person set age = 68 where id = 17;
rollback;
update person set age = 56 where id = 42;
commit;
insert into person (id, age) values (2, 81);
commit;
insert into person (id, age) values (5, 49);
commit;
insert into person (id, age) values (91, 32);
commit;
insert into person (id, age) values (97, 51);
commit;
insert into person (id, age) values (23, 86);
commit;
insert into person (id, age) values (0, 80);
commit;
insert into person (id, age) values (58, 92);
commit;
insert into person (id, age) values (75, 93);
commit;
insert into person (id, age) values (52, 46);
rollback;
insert into person (id, age) values (18, 25);
commit;
update person set age = 23 where id = 83;
commit;
update person set age = 6 where id = 34;
commit;
insert into person (id, age) values (63, 61);
commit;
insert into person (id, age) values (45, 96);
commit;
update person set age = 40 where id = 20;
commit;
delete from person where id = 20;
rollback;
insert into person (id, age) values (40, 91);
commit;
update person set age = 75 where id = 83;
commit;
delete from person where id = 91;
rollback;
delete from person where id = 63;
commit;
delete from person where id = 56;
rollback;
insert into person (id, age) values (70, 24);
commit;
delete from person where id = 91;
commit;
insert into person (id, age) values (33, 77);
commit;
update person set age = 97 where id = 25;
commit;
insert into person (id, age) values (74, 71);
commit;
update person set age = 54 where id = 14;
commit;
delete from person where id = 21;
commit;
insert into person (id, age) values (11, 57);
commit;
delete from person where id = 56;
commit;
insert into person (id, age) values (90, 78);
commit;
insert into person (id, age) values (96, 95);
commit;
insert into person (id, age) values (59, 4);
commit;
update person set age = 69 where id = 74;
commit;
update person set age = 96 where id = 10;
commit;
update person set age = 10 where id = 96;
commit;
insert into person (id, age) values (85, 80);
rollback;
update person set age = 80 where id = 53;
commit;
insert into person (id, age) values (84, 19);
commit;
delete from person where id = 62;
commit;
insert into person (id, age) values (8, 35);
commit;
insert into person (id, age) values (44, 47);
commit;
insert into person (id, age) values (94, 1);
commit;
update person set age = 60 where id = 20;
commit;
update person set age = 77 where id = 45;
commit;
update person set age = 38 where id = 70;
commit;
insert into person (id, age) values (24, 92);
commit;
insert into person (id, age) values (12, 23);
commit;
update person set age = 80 where id = 44;
rollback;
insert into person (id, age) values (86, 98);
commit;
insert into person (id, age) values (60, 72);
commit;
update person set age = 54 where id = 94;
commit;
insert into person (id, age) values (54, 35);
commit;
insert into person (id, age) values (21, 40);
commit;
update person set age = 87 where id = 70;
commit;
insert into person (id, age) values (92, 83);
rollback;
insert into person (id, age) values (61, 12);
commit;
update person set age = 83 where id = 24;
commit;
insert into person (id, age) values (31, 85);
commit;
insert into person (id, age) values (50, 41);
commit;
update person set age = 27 where id = 39;
commit;
update person set age = 6 where id = 51;
commit;
insert into person (id, age) values (19, 86);
commit;
update person set age = 77 where id = 21;
rollback;
insert into person (id, age) values (65, 37);
commit;
insert into person (id, age) values (87, 40);
commit;
insert into person (id, age) values (43, 42);
commit;
update person set age = 27 where id = 44;
commit;
insert into person (id, age) values (3, 57);
commit;
update person set age = 57 where id = 87;
commit;
update person set age = 28 where id = 11;
commit;
delete from person where id = 60;
rollback;
update person set age = 73 where id = 10;
commit;
update person set age = 58 where id = 8;
commit;
update person set age = 32 where id = 86;
commit;
insert into person (id, age) values (77, 6);
rollback;
update person set age = 37 where id = 21;
commit;
insert into person (id, age) values (88, 70);
commit;
insert into person (id, age) values (52, 18);
commit;
update person set age = 39 where id = 55;
commit;
update person set age = 49 where id = 24;
commit;
insert into person (id, age) values (89, 53);
commit;
insert into person (id, age) values (32, 49);
commit;
insert into person (id, age) values (95, 42);
commit;
update person set age = 72 where id = 93;
commit;
insert into person (id, age) values (66, 19);
commit;
update person set age = 47 where id = 51;
commit;
insert into person (id, age) values (48, 85);
commit;
update person set age = 73 where id = 87;
commit;
update person set age = 40 where id = 95;
commit;
insert into person (id, age) values (13, 71);
commit;
insert into person (id, age) values (30, 95);
commit;
insert into person (id, age) values (77, 1);
commit;
insert into person (id, age) values (4, 78);
commit;
insert into person (id, age) values (35, 15);
commit;
update person set age = 66 where id = 13;
rollback;
update person set age = 0 where id = 17;
commit;
update person set age = 88 where id = 97;
commit;
update person set age = 2 where id = 93;
commit;
update person set age = 86 where id = 14;
commit;
insert into person (id, age) values (85, 64);
commit;
update person set age = 75 where id = 31;
commit;
update person set age = 30 where id = 80;
commit;
update person set age = 38 where id = 22;
commit;
insert into person (id, age) values (68, 64);
commit;
update person set age = 76 where id = 47;
commit;
update person set age = 66 where id = 32;
commit;
update person set age = 17 where id = 51;
rollback;
update person set age = 77 where id = 77;
commit;
insert into person (id, age) values (98, 75);
commit;
update person set age = 16 where id = 42;
commit;
update person set age = 90 where id = 10;
commit;
insert into person (id, age) values (37, 55);
commit;
insert into person (id, age) values (26, 28);
commit;
delete from person where id = 66;
commit;
update person set age = 71 where id = 99;
commit;
insert into person (id, age) values (72, 0);
commit;
update person set age = 74 where id = 25;
commit;
update person set age = 13 where id = 38;
commit;
update person set age = 61 where id = 33;
commit;
update person set age = 60 where id = 8;
commit;
update person set age = 17 where id = 36;
rollback;
insert into person (id, age) values (9, 78);
commit;
insert into person (id, age) values (66, 59);
commit;
insert into person (id, age) values (69, 4);
rollback;
insert into person (id, age) values (92, 33);
commit;
update person set age = 56 where id = 19;
rollback;
update person set age = 60 where id = 66;
commit;
update person set age = 21 where id = 52;
commit;
update person set age = 9 where id = 93;
commit;
insert into person (id, age) values (49, 86);
commit;
update person set age = 29 where id = 10;
commit;
update person set age = 55 where id = 68;
commit;
update person set age = 42 where id = 34;
commit;
update person set age = 5 where id = 92;
commit;
update person set age = 54 where id = 95;
commit;
update person set age = 68 where id = 60;
commit;
delete from person where id = 21;
commit;
update person set age = 87 where id = 2;
commit;
insert into person (id, age) values (46, 53);
commit;
insert into person (id, age) values (62, 18);
commit;
update person set age = 98 where id = 53;
commit;
update person set age = 48 where id = 39;
commit;
update person set age = 12 where id = 67;
commit;
update person set age = 88 where id = 49;
commit;
update person set age = 28 where id = 67;
commit;
update person set age = 43 where id = 0;
commit;
delete from person where id = 83;
commit;
insert into person (id, age) values (15, 68);
commit;
delete from person where id = 23;
commit;
update person set age = 47 where id = 28;
rollback;
update person set age = 14 where id = 9;
commit;
update person set age = 19 where id = 44;
rollback;
update person set age = 27 where id = 72;
commit;
update person set age = 2 where id = 94;
commit;
update person set age = 81 where id = 14;
commit;
insert into person (id, age) values (79, 46);
commit;
update person set age = 46 where id = 89;
commit;
insert into person (id, age) values (41, 4);
commit;
update person set age = 20 where id = 48;
commit;
insert into person (id, age) values (64, 74);
rollback;
update person set age = 12 where id = 36;
commit;
update person set age = 64 where id = 87;
commit;
update person set age = 75 where id = 93;
commit;
update person set age = 63 where id = 70;
commit;
update person set age = 35 where id = 32;
commit;
update person set age = 20 where id = 12;
commit;
update person set age = 45 where id = 4;
commit;
update person set age = 29 where id = 80;
commit;
update person set age = 6 where id = 87;
commit;
insert into person (id, age) values (81, 26);
commit;
insert into person (id, age) values (27, 13);
commit;
update person set age = 89 where id = 35;
commit;
insert into person (id, age) values (83, 46);
commit;
update person set age = 34 where id = 97;
commit;
update person set age = 13 where id = 1;
commit;
insert into person (id, age) values (71, 51);
commit;
update person set age = 11 where id = 75;
commit;
update person set age = 84 where id = 11;
commit;
update person set age = 88 where id = 53;
commit;
update person set age = 60 where id = 54;
commit;
update person set age = 74 where id = 38;
commit;
insert into person (id, age) values (73, 74);
commit;
update person set age = 16 where id = 71;
commit;
update person set age = 8 where id = 34;
commit;
update person set age = 68 where id = 22;
commit;
insert into person (id, age) values (82, 71);
commit;
update person set age = 95 where id = 44;
commit;
update person set age = 9 where id = 73;
commit;
update person set age = 73 where id = 73;
commit;
update person set age = 29 where id = 39;
commit;
update person set age = 6 where id = 78;
commit;
update person set age = 85 where id = 15;
commit;
update person set age = 57 where id = 66;
commit;
update person set age = 46 where id = 40;
commit;
insert into person (id, age) values (91, 0);
commit;
update person set age = 14 where id = 58;
commit;
update person set age = 65 where id = 12;
rollback;
update person set age = 57 where id = 0;
commit;
update person set age = 94 where id = 86;
commit;
update person set age = 89 where id = 73;
commit;
insert into person (id, age) values (56, 10);
rollback;
update person set age = 50 where id = 80;
commit;
update person set age = 29 where id = 93;
commit;
insert into person (id, age) values (69, 25);
commit;
update person set age = 43 where id = 46;
commit;
delete from person where id = 60;
commit;
update person set age = 3 where id = 25;
commit;
update person set age = 30 where id = 71;
commit;
update person set age = 64 where id = 97;
commit;
insert into person (id, age) values (60, 11);
commit;
update person set age = 54 where id = 82;
commit;
insert into person (id, age) values (16, 57);
commit;
insert into person (id, age) values (6, 49);
commit;
delete from person where id = 10;
commit;
update person set age = 29 where id = 89;
commit;
update person set age = 92 where id = 77;
commit;
update person set age = 99 where id = 17;
commit;
update person set age = 1 where id = 42;
commit;
update person set age = 87 where id = 85;
commit;
delete from person where id = 66;
commit;
update person set age = 57 where id = 59;
commit;
update person set age = 48 where id = 80;
commit;
update person set age = 49 where id = 17;
commit;
update person set age = 43 where id = 95;
commit;
delete from person where id = 40;
commit;
update person set age = 82 where id = 74;
commit;
update person set age = 25 where id = 20;
commit;
update person set age = 21 where id = 28;
commit;
update person set age = 58 where id = 69;
commit;
update person set age = 52 where id = 41;
commit;
update person set age = 91 where id = 86;
commit;
update person set age = 87 where id = 54;
commit;
update person set age = 61 where id = 12;
commit;
update person set age = 66 where id = 60;
commit;
update person set age = 86 where id = 69;
commit;
update person set age = 25 where id = 5;
commit;
update person set age = 70 where id = 5;
commit;
update person set age = 5 where id = 16;
commit;
update person set age = 59 where id = 99;
commit;
update person set age = 57 where id = 35;
commit;
update person set age = 66 where id = 86;
rollback;
update person set age = 45 where id = 39;
commit;
update person set age = 67 where id = 62;
commit;
insert into person (id, age) values (21, 30);
commit;
insert into person (id, age) values (7, 84);
commit;
update person set age = 68 where id = 18;
commit;
update person set age = 34 where id = 82;
commit;
update person set age = 18 where id = 12;
rollback;
update person set age = 1 where id = 92;
commit;
update person set age = 97 where id = 13;
commit;
delete from person where id = 51;
rollback;
update person set age = 97 where id = 99;
commit;
update person set age = 66 where id = 44;
commit;
update person set age = 76 where id = 52;
commit;
update person set age = 63 where id = 88;
commit;
update person set age = 98 where id = 46;
commit;
update person set age = 57 where id = 84;
commit;
update person set age = 37 where id = 38;
commit;
insert into person (id, age) values (66, 98);
commit;
update person set age = 75 where id = 84;
commit;
update person set age = 98 where id = 25;
commit;
update person set age = 14 where id = 24;
commit;
update person set age = 99 where id = 54;
commit;
update person set age = 49 where id = 51;
commit;
update person set age = 14 where id = 26;
commit;
update person set age = 26 where id = 11;
commit;
delete from person where id = 20;
commit;
update person set age = 51 where id = 50;
commit;
update person set age = 44 where id = 58;
commit;
update person set age = 34 where id = 79;
rollback;
insert into person (id, age) values (56, 56);
commit;
update person set age = 88 where id = 60;
commit;
insert into person (id, age) values (40, 36);
commit;
insert into person (id, age) values (23, 56);
rollback;
update person set age = 46 where id = 55;
commit;
update person set age = 15 where id = 59;
rollback;
insert into person (id, age) values (10, 37);
commit;
delete from person where id = 16;
commit;
insert into person (id, age) values (57, 70);
commit;
update person set age = 48 where id = 94;
commit;
update person set age = 64 where id = 46;
commit;
update person set age = 50 where id = 21;
commit;
update person set age = 28 where id = 24;
commit;
update person set age = 71 where id = 43;
commit;
update person set age = 11 where id = 52;
rollback;
update person set age = 36 where id = 3;
commit;
delete from person where id = 19;
commit;
update person set age = 92 where id = 21;
commit;
update person set age = 73 where id = 96;
rollback;
update person set age = 65 where id = 40;
commit;
update person set age = 66 where id = 82;
commit;
delete from person where id = 90;
commit;
update person set age = 16 where id = 3;
commit;
update person set age = 42 where id = 50;
commit;
update person set age = 69 where id = 89;
commit;
update person set age = 83 where id = 50;
commit;
update person set age = 38 where id = 3;
commit;
update person set age = 2 where id = 13;
commit;
update person set age = 71 where id = 71;
commit;
update person set age = 31 where id = 61;
commit;
update person set age = 49 where id = 24;
commit;
insert into person (id, age) values (29, 45);
commit;
update person set age = 62 where id = 89;
commit;
update person set age = 43 where id = 83;
commit;
update person set age = 22 where id = 54;
commit;
update person set age = 92 where id = 35;
commit;
update person set age = 70 where id = 67;
commit;
update person set age = 20 where id = 21;
commit;
update person set age = 80 where id = 18;
commit;
update person set age = 82 where id = 6;
commit;
update person set age = 80 where id = 12;
commit;
update person set age = 37 where id = 68;
commit;
insert into person (id, age) values (64, 86);
commit;
update person set age = 81 where id = 53;
commit;
update person set age = 46 where id = 55;
commit;
update person set age = 41 where id = 59;
commit;
delete from person where id = 24;
commit;
update person set age = 58 where id = 86;
commit;
update person set age = 46 where id = 40;
commit;
insert into person (id, age) values (90, 43);
commit;
update person set age = 74 where id = 83;
commit;
update person set age = 14 where id = 22;
commit;
update person set age = 7 where id = 91;
commit;
update person set age = 85 where id = 22;
commit;
update person set age = 75 where id = 7;
commit;
delete from person where id = 81;
rollback;
update person set age = 79 where id = 93;
commit;
update person set age = 37 where id = 27;
commit;
update person set age = 99 where id = 31;
rollback;
update person set age = 77 where id = 61;
commit;
update person set age = 63 where id = 2;
commit;
delete from person where id = 29;
commit;
update person set age = 98 where id = 4;
commit;
update person set age = 58 where id = 96;
commit;
update person set age = 65 where id = 13;
commit;
insert into person (id, age) values (63, 33);
commit;
update person set age = 31 where id = 82;
commit;
update person set age = 84 where id = 1;
commit;
update person set age = 50 where id = 0;
commit;
update person set age = 18 where id = 44;
commit;
update person set age = 14 where id = 10;
rollback;
update person set age = 37 where id = 88;
commit;
update person set age = 46 where id = 79;
rollback;
update person set age = 18 where id = 4;
commit;
update person set age = 48 where id = 34;
commit;
update person set age = 75 where id = 33;
rollback;
update person set age = 69 where id = 11;
commit;
update person set age = 47 where id = 25;
commit;
update person set age = 22 where id = 33;
commit;
update person set age = 76 where id = 54;
commit;
update person set age = 20 where id = 11;
commit;
update person set age = 88 where id = 45;
commit;
update person set age = 60 where id = 60;
commit;
update person set age = 24 where id = 38;
commit;
update person set age = 91 where id = 1;
commit;
update person set age = 28 where id = 39;
commit;
delete from person where id = 74;
commit;
update person set age = 27 where id = 35;
commit;
update person set age = 96 where id = 21;
commit;
update person set age = 42 where id = 40;
commit;
update person set age = 49 where id = 2;
commit;
update person set age = 92 where id = 9;
commit;
delete from person where id = 61;
commit;
update person set age = 1 where id = 57;
commit;
update person set age = 97 where id = 53;
commit;
update person set age = 88 where id = 73;
rollback;
insert into person (id, age) values (20, 25);
commit;
update person set age = 13 where id = 17;
commit;
update person set age = 48 where id = 5;
commit;
update person set age = 44 where id = 9;
commit;
update person set age = 94 where id = 47;
commit;
update person set age = 37 where id = 34;
commit;
update person set age = 38 where id = 35;
commit;
update person set age = 98 where id = 2;
commit;
update person set age = 62 where id = 98;
commit;
update person set age = 16 where id = 6;
commit;
update person set age = 84 where id = 37;
commit;
delete from person where id = 53;
rollback;
update person set age = 8 where id = 28;
commit;
update person set age = 48 where id = 81;
commit;
delete from person where id = 28;
commit;
update person set age = 39 where id = 87;
commit;
update person set age = 13 where id = 71;
commit;
delete from person where id = 34;
commit;
update person set age = 8 where id = 38;
commit;
update person set age = 2 where id = 56;
commit;
update person set age = 4 where id = 65;
commit;
update person set age = 51 where id = 91;
rollback;
update person set age = 92 where id = 13;
commit;
delete from person where id = 54;
commit;
delete from person where id = 2;
commit;
delete from person where id = 70;
commit;
update person set age = 98 where id = 55;
commit;
update person set age = 61 where id = 48;
commit;
update person set age = 87 where id = 40;
commit;
insert into person (id, age) values (29, 63);
commit;
insert into person (id, age) values (74, 51);
commit;
update person set age = 99 where id = 8;
commit;
update person set age = 11 where id = 81;
commit;
update person set age = 52 where id = 11;
commit;
update person set age = 95 where id = 87;
rollback;
delete from person where id = 85;
commit;
update person set age = 81 where id = 41;
commit;
insert into person (id, age) values (19, 92);
commit;
update person set age = 21 where id = 55;
commit;
update person set age = 5 where id = 20;
commit;
update person set age = 86 where id = 75;
commit;
update person set age = 61 where id = 51;
commit;
update person set age = 25 where id = 81;
commit;
update person set age = 17 where id = 71;
commit;
update person set age = 12 where id = 74;
rollback;
update person set age = 27 where id = 0;
commit;
update person set age = 51 where id = 45;
commit;
update person set age = 29 where id = 83;
commit;
insert into person (id, age) values (85, 8);
commit;
update person set age = 43 where id = 21;
commit;
update person set age = 4 where id = 21;
commit;
update person set age = 33 where id = 31;
commit;
update person set age = 77 where id = 1;
commit;
update person set age = 87 where id = 45;
commit;
update person set age = 12 where id = 31;
commit;
update person set age = 51 where id = 49;
commit;
insert into person (id, age) values (16, 34);
commit;
update person set age = 19 where id = 52;
commit;
insert into person (id, age) values (54, 13);
commit;
update person set age = 53 where id = 18;
commit;
update person set age = 5 where id = 88;
commit;
update person set age = 96 where id = 40;
commit;
update person set age = 5 where id = 86;
commit;
insert into person (id, age) values (61, 30);
commit;
update person set age = 81 where id = 0;
commit;
update person set age = 58 where id = 97;
commit;
insert into person (id, age) values (70, 67);
commit;
update person set age = 41 where id = 51;
commit;
insert into person (id, age) values (34, 12);
commit;
update person set age = 55 where id = 48;
commit;
update person set age = 5 where id = 0;
commit;
update person set age = 8 where id = 33;
commit;
update person set age = 60 where id = 17;
commit;
update person set age = 0 where id = 12;
commit;
delete from person where id = 10;
commit;
update person set age = 70 where id = 18;
commit;
update person set age = 11 where id = 56;
commit;
update person set age = 11 where id = 85;
commit;
update person set age = 86 where id = 0;
commit;
update person set age = 61 where id = 43;
commit;
update person set age = 15 where id = 57;
commit;
update person set age = 0 where id = 60;
commit;
update person set age = 44 where id = 25;
commit;
update person set age = 53 where id = 36;
commit;
update person set age = 59 where id = 91;
commit;
insert into person (id, age) values (23, 97);
commit;
update person set age = 97 where id = 82;
commit;
update person set age = 34 where id = 56;
commit;
delete from person where id = 18;
rollback;
update person set age = 0 where id = 86;
commit;
update person set age = 26 where id = 41;
commit;
update person set age = 21 where id = 32;
commit;
update person set age = 89 where id = 97;
commit;
update person set age = 30 where id = 41;
rollback;
insert into person (id, age) values (28, 12);
commit;
update person set age = 27 where id = 7;
commit;
update person set age = 41 where id = 86;
commit;
delete from person where id = 83;
rollback;
update person set age = 43 where id = 44;
commit;
update person set age = 8 where id = 52;
commit;
update person set age = 52 where id = 12;
commit;
update person set age = 65 where id = 53;
commit;
update person set age = 60 where id = 20;
commit;
update person set age = 27 where id = 39;
commit;
update person set age = 15 where id = 61;
commit;
update person set age = 75 where id = 28;
commit;
update person set age = 2 where id = 25;
commit;
update person set age = 77 where id = 77;
commit;
update person set age = 4 where id = 12;
commit;
update person set age = 99 where id = 88;
rollback;
update person set age = 79 where id = 15;
rollback;
update person set age = 31 where id = 28;
rollback;
update person set age = 76 where id = 16;
commit;
update person set age = 48 where id = 90;
commit;
update person set age = 98 where id = 42;
commit;
update person set age = 88 where id = 84;
commit;
update person set age = 19 where id = 71;
rollback;
update person set age = 20 where id = 41;
commit;
update person set age = 56 where id = 38;
commit;
update person set age = 41 where id = 29;
commit;
delete from person where id = 41;
commit;
insert into person (id, age) values (76, 51);
commit;
update person set age = 5 where id = 12;
commit;
update person set age = 51 where id = 94;
commit;
update person set age = 10 where id = 45;
commit;
update person set age = 92 where id = 57;
commit;
update person set age = 10 where id = 30;
commit;
update person set age = 21 where id = 69;
commit;
update person set age = 31 where id = 6;
commit;
update person set age = 69 where id = 12;
commit;
update person set age = 32 where id = 61;
commit;
update person set age = 4 where id = 94;
commit;
update person set age = 90 where id = 95;
commit;
update person set age = 77 where id = 43;
rollback;
insert into person (id, age) values (2, 48);
commit;
update person set age = 20 where id = 0;
commit;
update person set age = 80 where id = 98;
commit;
update person set age = 35 where id = 21;
commit;
update person set age = 97 where id = 88;
commit;
update person set age = 59 where id = 32;
rollback;
update person set age = 41 where id = 30;
commit;
update person set age = 21 where id = 8;
commit;
delete from person where id = 94;
commit;
update person set age = 34 where id = 66;
commit;
delete from person where id = 57;
rollback;
update person set age = 70 where id = 59;
commit;
update person set age = 45 where id = 30;
commit;
insert into person (id, age) values (41, 64);
commit;
update person set age = 15 where id = 47;
commit;
update person set age = 85 where id = 3;
commit;
update person set age = 50 where id = 61;
commit;
update person set age = 94 where id = 39;
commit;
delete from person where id = 14;
commit;
update person set age = 91 where id = 79;
commit;
update person set age = 84 where id = 5;
commit;
delete from person where id = 71;
commit;
update person set age = 4 where id = 58;
commit;
update person set age = 99 where id = 26;
commit;
update person set age = 17 where id = 52;
commit;
update person set age = 9 where id = 98;
commit;
update person set age = 51 where id = 80;
commit;
update person set age = 53 where id = 6;
commit;
update person set age = 65 where id = 75;
commit;
update person set age = 70 where id = 22;
rollback;
update person set age = 7 where id = 58;
commit;
delete from person where id = 98;
commit;
update person set age = 38 where id = 69;
commit;
insert into person (id, age) values (71, 55);
commit;
update person set age = 90 where id = 46;
commit;
update person set age = 32 where id = 15;
rollback;
update person set age = 57 where id = 30;
commit;
insert into person (id, age) values (24, 79);
commit;
delete from person where id = 54;
commit;
update person set age = 50 where id = 26;
commit;
update person set age = 16 where id = 15;
commit;
delete from person where id = 57;
commit;
update person set age = 66 where id = 88;
commit;
update person set age = 77 where id = 32;
commit;
update person set age = 42 where id = 56;
commit;
update person set age = 33 where id = 65;
commit;
update person set age = 76 where id = 11;
commit;
update person set age = 75 where id = 9;
commit;
update person set age = 40 where id = 59;
commit;
insert into person (id, age) values (14, 75);
commit;
update person set age = 30 where id = 35;
commit;
update person set age = 6 where id = 40;
rollback;
update person set age = 97 where id = 40;
commit;
update person set age = 49 where id = 18;
commit;
update person set age = 75 where id = 42;
commit;
update person set age = 1 where id = 44;
commit;
update person set age = 18 where id = 42;
commit;
update person set age = 20 where id = 16;
commit;
update person set age = 72 where id = 87;
commit;
update person set age = 18 where id = 15;
commit;
update person set age = 4 where id = 26;
commit;
update person set age = 12 where id = 35;
commit;
update person set age = 26 where id = 83;
commit;
update person set age = 65 where id = 24;
commit;
update person set age = 31 where id = 84;
commit;
update person set age = 15 where id = 5;
commit;
update person set age = 18 where id = 39;
commit;
update person set age = 38 where id = 46;
commit;
insert into person (id, age) values (98, 59);
commit;
update person set age = 8 where id = 93;
commit;
update person set age = 47 where id = 56;
commit;
update person set age = 33 where id = 38;
commit;
update person set age = 33 where id = 62;
commit;
delete from person where id = 0;
commit;
update person set age = 85 where id = 85;
commit;
insert into person (id, age) values (0, 28);
commit;
update person set age = 40 where id = 31;
rollback;
update person set age = 11 where id = 91;
commit;
update person set age = 83 where id = 19;
commit;
delete from person where id = 84;
commit;
update person set age = 75 where id = 27;
commit;
update person set age = 60 where id = 9;
commit;
update person set age = 84 where id = 88;
commit;
update person set age = 31 where id = 39;
commit;
update person set age = 81 where id = 21;
rollback;
update person set age = 38 where id = 64;
commit;
insert into person (id, age) values (10, 1);
commit;
update person set age = 48 where id = 44;
rollback;
update person set age = 36 where id = 15;
commit;
update person set age = 79 where id = 13;
commit;
update person set age = 22 where id = 49;
rollback;
update person set age = 26 where id = 58;
commit;
update person set age = 91 where id = 98;
commit;
update person set age = 11 where id = 2;
commit;
update person set age = 44 where id = 39;
commit;
update person set age = 13 where id = 53;
commit;
update person set age = 76 where id = 15;
commit;
update person set age = 6 where id = 51;
commit;
update person set age = 8 where id = 62;
commit;
update person set age = 57 where id = 17;
commit;
update person set age = 25 where id = 45;
commit;
update person set age = 84 where id = 93;
commit;
delete from person where id = 14;
commit;
update person set age = 71 where id = 96;
commit;
update person set age = 79 where id = 45;
rollback;
update person set age = 60 where id = 83;
commit;
update person set age = 41 where id = 30;
commit;
update person set age = 96 where id = 55;
commit;
update person set age = 10 where id = 93;
commit;
update person set age = 16 where id = 41;
commit;
update person set age = 69 where id = 81;
commit;
update person set age = 58 where id = 36;
commit;
update person set age = 90 where id = 52;
commit;
update person set age = 70 where id = 66;
rollback;
update person set age = 52 where id = 55;
commit;
update person set age = 85 where id = 17;
commit;
update person set age = 92 where id = 0;
commit;
update person set age = 56 where id = 91;
rollback;
update person set age = 65 where id = 30;
rollback;
update person set age = 66 where id = 45;
rollback;
update person set age = 96 where id = 5;
commit;
update person set age = 55 where id = 87;
commit;
update person set age = 4 where id = 87;
commit;
update person set age = 45 where id = 2;
commit;
delete from person where id = 93;
rollback;
update person set age = 36 where id = 87;
commit;
update person set age = 96 where id = 59;
commit;
update person set age = 99 where id = 89;
commit;
delete from person where id = 39;
commit;
update person set age = 53 where id = 16;
commit;
update person set age = 47 where id = 82;
commit;
update person set age = 96 where id = 87;
commit;
update person set age = 1 where id = 13;
commit;
update person set age = 90 where id = 48;
commit;
update person set age = 36 where id = 37;
commit;
update person set age = 21 where id = 34;
commit;
update person set age = 63 where id = 81;
commit;
delete from person where id = 19;
commit;
update person set age = 56 where id = 79;
commit;
update person set age = 7 where id = 5;
commit;
delete from person where id = 12;
commit;
update person set age = 37 where id = 89;
rollback;
update person set age = 22 where id = 18;
commit;
delete from person where id = 50;
commit;
update person set age = 49 where id = 16;
commit;
update person set age = 81 where id = 78;
commit;
update person set age = 24 where id = 24;
commit;
update person set age = 86 where id = 26;
commit;
update person set age = 69 where id = 23;
commit;
update person set age = 66 where id = 99;
commit;
update person set age = 26 where id = 58;
commit;
update person set age = 44 where id = 83;
commit;
update person set age = 41 where id = 13;
commit;
insert into person (id, age) values (57, 19);
commit;
update person set age = 72 where id = 21;
commit;
update person set age = 7 where id = 9;
commit;
delete from person where id = 93;
commit;
update person set age = 63 where id = 46;
commit;
update person set age = 7 where id = 57;
commit;
update person set age = 37 where id = 64;
rollback;
update person set age = 70 where id = 69;
commit;
delete from person where id = 96;
commit;
update person set age = 45 where id = 73;
commit;
update person set age = 11 where id = 91;
commit;
update person set age = 95 where id = 48;
commit;
update person set age = 58 where id = 83;
commit;
update person set age = 0 where id = 49;
commit;
update person set age = 94 where id = 66;
commit;
update person set age = 11 where id = 43;
commit;
update person set age = 44 where id = 97;
commit;
delete from person where id = 79;
commit;
update person set age = 93 where id = 2;
commit;
update person set age = 92 where id = 75;
commit;
update person set age = 30 where id = 58;
commit;
update person set age = 35 where id = 99;
commit;
update person set age = 87 where id = 95;
commit;
insert into person (id, age) values (14, 78);
commit;
update person set age = 29 where id = 14;
commit;
update person set age = 1 where id = 15;
commit;
update person set age = 61 where id = 95;
commit;
insert into person (id, age) values (94, 76);
commit;
update person set age = 13 where id = 30;
commit;
update person set age = 71 where id = 64;
commit;
insert into person (id, age) values (79, 19);
commit;
delete from person where id = 56;
commit;
update person set age = 74 where id = 13;
commit;
update person set age = 6 where id = 43;
commit;
update person set age = 34 where id = 10;
commit;
update person set age = 8 where id = 31;
commit;
update person set age = 85 where id = 13;
rollback;
update person set age = 81 where id = 22;
commit;
update person set age = 26 where id = 90;
commit;
update person set age = 86 where id = 81;
commit;
update person set age = 58 where id = 45;
commit;
update person set age = 22 where id = 46;
commit;
update person set age = 3 where id = 23;
rollback;
update person set age = 35 where id = 98;
commit;
insert into person (id, age) values (56, 23);
commit;
delete from person where id = 72;
commit;
update person set age = 72 where id = 4;
commit;
insert into person (id, age) values (96, 53);
commit;
update person set age = 88 where id = 60;
commit;
update person set age = 14 where id = 95;
commit;
update person set age = 80 where id = 59;
commit;
update person set age = 92 where id = 51;
commit;
update person set age = 52 where id = 23;
commit;
update person set age = 83 where id = 46;
commit;
update person set age = 57 where id = 22;
commit;
update person set age = 30 where id = 63;
commit;
delete from person where id = 33;
commit;
update person set age = 8 where id = 71;
commit;
insert into person (id, age) values (19, 98);
commit;
update person set age = 36 where id = 46;
rollback;
update person set age = 11 where id = 92;
commit;
delete from person where id = 59;
commit;
update person set age = 2 where id = 83;
commit;
update person set age = 14 where id = 91;
commit;
delete from person where id = 38;
commit;
update person set age = 2 where id = 87;
rollback;
update person set age = 85 where id = 35;
commit;
update person set age = 52 where id = 5;
rollback;
update person set age = 29 where id = 35;
commit;
update person set age = 6 where id = 46;
commit;
update person set age = 17 where id = 2;
commit;
insert into person (id, age) values (59, 42);
commit;
update person set age = 82 where id = 88;
rollback;
delete from person where id = 5;
commit;
update person set age = 72 where id = 36;
commit;
update person set age = 46 where id = 16;
commit;
update person set age = 4 where id = 19;
rollback;
update person set age = 9 where id = 92;
commit;
update person set age = 29 where id = 0;
commit;
update person set age = 37 where id = 65;
commit;
update person set age = 22 where id = 26;
rollback;
update person set age = 21 where id = 74;
commit;
update person set age = 93 where id = 35;
commit;
delete from person where id = 73;
commit;
update person set age = 21 where id = 29;
commit;
update person set age = 42 where id = 85;
commit;
update person set age = 32 where id = 27;
commit;
update person set age = 49 where id = 2;
commit;
update person set age = 17 where id = 55;
commit;
update person set age = 97 where id = 14;
commit;
update person set age = 92 where id = 19;
commit;
update person set age = 92 where id = 71;
commit;
delete from person where id = 11;
commit;
delete from person where id = 31;
commit;
update person set age = 85 where id = 85;
commit;
update person set age = 42 where id = 13;
commit;
insert into person (id, age) values (39, 48);
commit;
update person set age = 8 where id = 42;
rollback;
update person set age = 40 where id = 43;
commit;
update person set age = 13 where id = 94;
commit;
update person set age = 75 where id = 83;
commit;
update person set age = 2 where id = 41;
commit;
update person set age = 43 where id = 99;
commit;
update person set age = 86 where id = 18;
commit;
update person set age = 98 where id = 19;
commit;
update person set age = 27 where id = 49;
commit;
update person set age = 50 where id = 30;
rollback;
delete from person where id = 44;
commit;
insert into person (id, age) values (50, 67);
commit;
update person set age = 12 where id = 9;
commit;
update person set age = 25 where id = 21;
commit;
update person set age = 82 where id = 6;
commit;
update person set age = 0 where id = 82;
commit;
update person set age = 84 where id = 20;
commit;
update person set age = 17 where id = 60;
commit;
update person set age = 55 where id = 55;
commit;
update person set age = 32 where id = 15;
commit;
update person set age = 69 where id = 0;
commit;
update person set age = 52 where id = 13;
commit;
update person set age = 70 where id = 62;
commit;
update person set age = 84 where id = 8;
commit;
update person set age = 28 where id = 76;
rollback;
update person set age = 10 where id = 61;
commit;
update person set age = 48 where id = 88;
commit;
delete from person where id = 85;
commit;
update person set age = 17 where id = 32;
commit;
update person set age = 25 where id = 91;
commit;
insert into person (id, age) values (38, 10);
commit;
update person set age = 78 where id = 39;
commit;
insert into person (id, age) values (73, 80);
commit;
update person set age = 76 where id = 73;
commit;
update person set age = 47 where id = 37;
commit;
update person set age = 72 where id = 22;
commit;
update person set age = 77 where id = 68;
commit;
insert into person (id, age) values (72, 72);
commit;
insert into person (id, age) values (33, 29);
commit;
update person set age = 13 where id = 28;
commit;
update person set age = 21 where id = 75;
commit;
insert into person (id, age) values (54, 21);
commit;
update person set age = 72 where id = 2;
commit;
update person set age = 17 where id = 69;
commit;
update person set age = 36 where id = 50;
rollback;
update person set age = 71 where id = 37;
commit;
update person set age = 13 where id = 36;
commit;
update person set age = 36 where id = 35;
commit;
update person set age = 15 where id = 54;
commit;
update person set age = 91 where id = 17;
commit;
update person set age = 8 where id = 59;
commit;
update person set age = 64 where id = 60;
commit;
update person set age = 91 where id = 46;
commit;
update person set age = 5 where id = 80;
commit;
update person set age = 81 where id = 38;
commit;
update person set age = 88 where id = 36;
commit;
update person set age = 75 where id = 69;
commit;
update person set age = 90 where id = 35;
rollback;
update person set age = 29 where id = 14;
commit;
update person set age = 97 where id = 39;
commit;
update person set age = 68 where id = 17;
commit;
update person set age = 55 where id = 50;
commit;
update person set age = 36 where id = 87;
commit;
update person set age = 96 where id = 6;
commit;
delete from person where id = 89;
commit;
insert into person (id, age) values (12, 64);
commit;
update person set age = 62 where id = 0;
commit;
update person set age = 94 where id = 3;
commit;
update person set age = 89 where id = 66;
commit;
update person set age = 26 where id = 15;
commit;
update person set age = 19 where id = 50;
rollback;
update person set age = 65 where id = 88;
commit;
update person set age = 39 where id = 40;
commit;
update person set age = 3 where id = 9;
commit;
update person set age = 36 where id = 53;
commit;
update person set age = 28 where id = 71;
commit;
delete from person where id = 36;
rollback;
update person set age = 16 where id = 92;
commit;
update person set age = 33 where id = 76;
commit;
update person set age = 89 where id = 36;
commit;
update person set age = 84 where id = 70;
commit;
update person set age = 90 where id = 58;
commit;
update person set age = 42 where id = 72;
commit;
update person set age = 53 where id = 42;
commit;
update person set age = 34 where id = 37;
commit;
update person set age = 78 where id = 8;
commit;
update person set age = 90 where id = 27;
rollback;
update person set age = 96 where id = 15;
commit;
update person set age = 23 where id = 9;
commit;
update person set age = 95 where id = 29;
rollback;
update person set age = 92 where id = 36;
rollback;
update person set age = 48 where id = 7;
commit;
update person set age = 55 where id = 53;
commit;
delete from person where id = 45;
commit;
update person set age = 70 where id = 77;
commit;
update person set age = 21 where id = 72;
rollback;
update person set age = 70 where id = 59;
commit;
update person set age = 24 where id = 23;
commit;
update person set age = 43 where id = 35;
rollback;
update person set age = 60 where id = 97;
commit;
update person set age = 80 where id = 55;
commit;
update person set age = 0 where id = 48;
commit;
delete from person where id = 14;
commit;
update person set age = 36 where id = 48;
commit;
update person set age = 6 where id = 69;
commit;
update person set age = 97 where id = 57;
commit;
update person set age = 64 where id = 99;
commit;
update person set age = 19 where id = 60;
commit;
update person set age = 79 where id = 29;
commit;
update person set age = 16 where id = 72;
commit;
insert into person (id, age) values (89, 60);
commit;
delete from person where id = 27;
commit;
update person set age = 37 where id = 68;
commit;
insert into person (id, age) values (93, 29);
commit;
update person set age = 55 where id = 68;
commit;
update person set age = 16 where id = 87;
commit;
insert into person (id, age) values (5, 85);
commit;
update person set age = 30 where id = 93;
commit;
update person set age = 12 where id = 64;
commit;
update person set age = 47 where id = 55;
commit;
update person set age = 87 where id = 77;
rollback;
update person set age = 9 where id = 43;
commit;
update person set age = 35 where id = 83;
commit;
delete from person where id = 71;
commit;
update person set age = 45 where id = 29;
rollback;
insert into person (id, age) values (45, 5);
commit;
update person set age = 14 where id = 65;
commit;
update person set age = 14 where id = 29;
commit;
update person set age = 77 where id = 97;
rollback;
update person set age = 98 where id = 80;
commit;
delete from person where id = 87;
rollback;
update person set age = 98 where id = 15;
commit;
update person set age = 9 where id = 55;
commit;
delete from person where id = 49;
commit;
update person set age = 57 where id = 15;
commit;
update person set age = 98 where id = 33;
commit;
insert into person (id, age) values (27, 12);
commit;
update person set age = 99 where id = 87;
commit;
update person set age = 97 where id = 37;
commit;
update person set age = 90 where id = 45;
commit;
update person set age = 89 where id = 32;
commit;
update person set age = 32 where id = 32;
commit;
insert into person (id, age) values (31, 45);
commit;
update person set age = 7 where id = 47;
commit;
update person set age = 44 where id = 55;
rollback;
delete from person where id = 57;
commit;
insert into person (id, age) values (14, 82);
commit;
update person set age = 80 where id = 4;
commit;
update person set age = 95 where id = 77;
commit;
insert into person (id, age) values (49, 35);
commit;
update person set age = 41 where id = 60;
commit;
update person set age = 25 where id = 50;
commit;
update person set age = 51 where id = 68;
commit;
update person set age = 30 where id = 89;
commit;
update person set age = 7 where id = 8;
commit;
update person set age = 74 where id = 7;
commit;
delete from person where id = 90;
commit;
update person set age = 58 where id = 23;
commit;
update person set age = 79 where id = 68;
commit;
update person set age = 81 where id = 39;
commit;
update person set age = 98 where id = 46;
commit;
update person set age = 3 where id = 35;
commit;
update person set age = 38 where id = 9;
rollback;
update person set age = 19 where id = 2;
commit;
update person set age = 34 where id = 63;
commit;
update person set age = 45 where id = 40;
commit;
update person set age = 44 where id = 2;
commit;
update person set age = 39 where id = 75;
commit;
update person set age = 43 where id = 54;
commit;
update person set age = 36 where id = 0;
rollback;
update person set age = 67 where id = 35;
commit;
update person set age = 35 where id = 5;
commit;
update person set age = 32 where id = 24;
commit;
update person set age = 0 where id = 42;
commit;
update person set age = 75 where id = 56;
commit;
update person set age = 22 where id = 58;
rollback;
update person set age = 27 where id = 74;
commit;
delete from person where id = 94;
commit;
delete from person where id = 98;
commit;
update person set age = 17 where id = 46;
commit;
update person set age = 95 where id = 92;
commit;
update person set age = 95 where id = 82;
commit;
update person set age = 68 where id = 64;
rollback;
update person set age = 85 where id = 27;
commit;
delete from person where id = 91;
commit;
update person set age = 94 where id = 34;
commit;
update person set age = 84 where id = 19;
rollback;
delete from person where id = 54;
commit;
update person set age = 24 where id = 20;
commit;
update person set age = 75 where id = 60;
commit;
update person set age = 32 where id = 23;
rollback;
insert into person (id, age) values (85, 18);
rollback;
update person set age = 89 where id = 83;
commit;
insert into person (id, age) values (94, 51);
commit;
update person set age = 53 where id = 56;
commit;
insert into person (id, age) values (44, 62);
commit;
update person set age = 69 where id = 20;
commit;
update person set age = 55 where id = 94;
commit;
update person set age = 39 where id = 17;
commit;
update person set age = 62 where id = 15;
commit;
update person set age = 19 where id = 64;
commit;
update person set age = 71 where id = 37;
commit;

 */
