#!/bin/bash

# MapR VM Splice Machine DB cleaner

echo "Cleaning Splice Machine MapR DB"

# TODO Use zookeeper's cli to rmr /startupPath, then bounce hbase
# see also, SpliceMasterObserver.createSplice()


