#!/bin/bash

# Generic VM Splice Machine installer

pushd lib

# sets VM specific env vars
. ./setEnv

echo "Installing Splice Machine into $SPLICE_ENV"

SPLICE_GENERIC_JAR="splice_machine_complete.jar"

# Copy splice distribution jar to generic jar name
# grep makes sure we have the dist jar here and not both dist and linked (if link exists already)
# TODO - in case of upgrade, need to parse dist jar name and find latest vers
REAL_SPLICE_JAR_NAME=`/bin/ls *_complete.jar | grep $SPLICE_ENV`
# DEBUG
#echo "Source name: $REAL_SPLICE_JAR_NAME"
#echo "Target name: $SPLICE_GENERIC_JAR"
if [ -e $SPLICE_GENERIC_JAR ]; then
#    echo "Exists, unlinking"
    sudo /bin/rm $SPLICE_GENERIC_JAR
fi
#echo "copy $REAL_SPLICE_JAR_NAME $SPLICE_GENERIC_JAR"
sudo /bin/cp $REAL_SPLICE_JAR_NAME $HBASE_LIB/$SPLICE_GENERIC_JAR

# TODO - need to install splice coprocessors

popd