#!/bin/bash

# Generic VM Splice Machine installer

pushd lib>/dev/null

# sets VM specific env vars
. ./setEnv

echo "Installing Splice Machine into $SPLICE_ENV"

SPLICE_GENERIC_JAR="splice_machine_complete.jar"

# Copy versioned splice jar to a generically named jar in hbase/lib
# TODO - in case of upgrade, need to parse dist jar name and find latest vers
REAL_SPLICE_JAR_NAME=`/bin/ls *_complete.jar | grep $SPLICE_ENV`
# DEBUG
#echo "copy $REAL_SPLICE_JAR_NAME $SPLICE_GENERIC_JAR"
/usr/bin/sudo /bin/cp "$REAL_SPLICE_JAR_NAME" "$HBASE_LIB/$SPLICE_GENERIC_JAR"

# Call env specific script to install splice observer/coprocessors
./config

popd>/dev/null
