#!/bin/bash

# Generic Splice Machine SQL Shell

CLASSPATH=""

# sets VM specific env vars
source setEnv

echo "Running Splice Machine SQL shell"

CLASSPATH=$HBASE_HOME/hbase.jar:$HBASE_LIB/*

# connect 'jdbc:derby://localhost:1527/splicedb';
java -cp $CLASSPATH -Djdbc.drivers=org.apache.derby.jdbc.ClientDriver org.apache.derby.tools.ij $*

