set schema troc;
truncate table product;
drop table product;

create table 
TROC.PRODUCT 
( 
CUSTOMER_PRODUCT_ID INTEGER NOT NULL PRIMARY KEY, 
SHIPPED_DATE TIMESTAMP WITH DEFAULT CURRENT_TIMESTAMP, 
SOURCE_SYS_CREATE_DTS TIMESTAMP WITH DEFAULT CURRENT_TIMESTAMP NOT NULL,
SOURCE_SYS_UPDATE_DTS TIMESTAMP WITH DEFAULT CURRENT_TIMESTAMP NOT NULL,
SDR_CREATE_DATE TIMESTAMP WITH DEFAULT CURRENT_TIMESTAMP, 
SDR_UPDATE_DATE TIMESTAMP WITH DEFAULT CURRENT_TIMESTAMP,
DW_SRC_EXTRC_DTTM TIMESTAMP WITH DEFAULT CURRENT_TIMESTAMP
);

