package com.splicemachine.derby.utils;

import com.google.common.collect.Lists;
import com.gotometrics.orderly.IntegerRowKey;
import com.gotometrics.orderly.StringRowKey;

import org.apache.hadoop.hbase.util.Bytes;
import org.junit.Assert;
import org.junit.Test;

import java.util.Collections;
import java.util.List;

/**
 * Tests around confirming the behavior of RowKey and/or the underlying byte[] generated by RowKey entities.
 *
 * @author Scott Fines
 * Created on: 5/13/13
 */
public class RowKeyTest {

    @Test
    public void testStringAndIntegerSorting() throws Exception {
        /*
         * Make sure that IntegerRowKey generates bytes which sort with
         * a deterministic order w.r.t. a fixed String byte array
          */

        byte[] fixedString = new StringRowKey().serialize("tid");

        IntegerRowKey colKey = new IntegerRowKey();

        List<byte[]> bytes = Lists.newArrayList();
        for(int i=0;i<10000;i++){
            bytes.add(colKey.serialize(i));
        }
        bytes.add(fixedString);

        Collections.sort(bytes, new Bytes.ByteArrayComparator());
        Assert.assertEquals(fixedString, bytes.get(0));


    }
}
